version: '3.9'

services:
  ebpf-dev:
    build:
      context: .
      dockerfile: Dockerfile
      # If you’re on M1, pick one. Don’t declare multiple platforms unless you’re using buildx.
      # platforms: [ "linux/arm64" ]
    platform: linux/arm64

    container_name: capsule-ebpf
    privileged: true

    # Required so the container sees host tracepoints and BPF FS
    volumes:
      - .:/workspace
      - /sys:/sys
      - /lib/modules:/lib/modules:ro
      - ebpf-cargo-cache:/root/.cargo
      - ebpf-target-cache:/workspace/target

    working_dir: /workspace
    tty: true
    stdin_open: true

    # Give BPF room on older kernels
    ulimits:
      memlock:
        soft: -1
        hard: -1

    # Keep env simple; llvm prefix env often causes more harm than good
    environment:
      - BPF_CLANG=clang
      - CARGO_TARGET_DIR=/workspace/target

    # The Dockerfile’s entrypoint auto-mounts bpffs/tracefs at start.
    # You can override the command to run your app directly, e.g.:
    # command: ["/workspace/target/release/trace"]
    command: ['/bin/bash']

volumes:
  ebpf-cargo-cache:
  ebpf-target-cache:
