# ── docker-compose.yml ───────────────────────────────────────────────────────
services:
  agent:
    build: .
    container_name: capsule_agents_dev
    stdin_open: true
    tty: true
    ports:
      - '8000:8000' # ← expose container's 8000 on host:8000
    volumes:
      - ./:/app # hot-reload code during dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
